# Location constraints for differential reference clock buffers
# Note: the IP core-level XDC constrains the transceiver channel data pin locations
# ----------------------------------------------------------------------------------------------------------------------
set_property package_pin J30 [get_ports mgtrefclk1_x0y4_n]
set_property package_pin J29 [get_ports mgtrefclk1_x0y4_p]
set_property package_pin T5 [get_ports mgtrefclk1_x1y2_n]
set_property package_pin T6 [get_ports mgtrefclk1_x1y2_p]

# Location constraints for other example design top-level ports
# ----------------------------------------------------------------------------------------------------------------------
set_property package_pin W25 [get_ports hb_gtwiz_reset_clk_freerun_in_p]
set_property iostandard  LVDS [get_ports hb_gtwiz_reset_clk_freerun_in_p]
set_property package_pin Y25 [get_ports hb_gtwiz_reset_clk_freerun_in_n]
set_property iostandard  LVDS [get_ports hb_gtwiz_reset_clk_freerun_in_n]

#PUSHBUTTON[0]
set_property package_pin AB29 [get_ports hb_gtwiz_reset_all_in]     
set_property iostandard  LVCMOS18 [get_ports hb_gtwiz_reset_all_in] 

#PUSHBUTTON[1]
set_property package_pin AA29 [get_ports link_down_latched_reset_in]     
set_property iostandard  LVCMOS18 [get_ports link_down_latched_reset_in]

#LED0
set_property package_pin AC22 [get_ports link_status_out]                
set_property iostandard  LVCMOS18 [get_ports link_status_out]

#LED1
set_property package_pin AD25 [get_ports link_down_latched_out]          
set_property iostandard  LVCMOS18 [get_ports link_down_latched_out]  

#set_property IOSTANDARD LVDS [get_ports {AUX_dn[0]}]
#set_property PACKAGE_PIN U22 [get_ports {AUX_dn[0]}]
set_property IOSTANDARD LVDS [get_ports {AUX_dn[1]}]
set_property PACKAGE_PIN U25 [get_ports {AUX_dn[1]}]
#set_property IOSTANDARD LVDS [get_ports {AUX_dn[2]}]
#set_property PACKAGE_PIN W24 [get_ports {AUX_dn[2]}]
#set_property IOSTANDARD LVDS [get_ports {AUX_dn[3]}]
#set_property PACKAGE_PIN V28 [get_ports {AUX_dn[3]}]
#set_property IOSTANDARD LVDS [get_ports {AUX_dp[0]}]
#set_property PACKAGE_PIN U21 [get_ports {AUX_dp[0]}]
set_property IOSTANDARD LVDS [get_ports {AUX_dp[1]}]
set_property PACKAGE_PIN U24 [get_ports {AUX_dp[1]}]
#set_property IOSTANDARD LVDS [get_ports {AUX_dp[2]}]
#set_property PACKAGE_PIN W23 [get_ports {AUX_dp[2]}]
#set_property IOSTANDARD LVDS [get_ports {AUX_dp[3]}]
#set_property PACKAGE_PIN V27 [get_ports {AUX_dp[3]}]

set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[0]}]
set_property PACKAGE_PIN C14 [get_ports {ALPIDE_DATA_GPIO_dn[0]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[1]}]
set_property PACKAGE_PIN C13 [get_ports {ALPIDE_DATA_GPIO_dn[1]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[2]}]
set_property PACKAGE_PIN E13 [get_ports {ALPIDE_DATA_GPIO_dn[2]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[3]}]
set_property PACKAGE_PIN B11 [get_ports {ALPIDE_DATA_GPIO_dn[3]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[4]}]
set_property PACKAGE_PIN B12 [get_ports {ALPIDE_DATA_GPIO_dn[4]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[5]}]
set_property PACKAGE_PIN G12 [get_ports {ALPIDE_DATA_GPIO_dn[5]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[6]}]
set_property PACKAGE_PIN D11 [get_ports {ALPIDE_DATA_GPIO_dn[6]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[7]}]
set_property PACKAGE_PIN D10 [get_ports {ALPIDE_DATA_GPIO_dn[7]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[8]}]
set_property PACKAGE_PIN C8 [get_ports {ALPIDE_DATA_GPIO_dn[8]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[9]}]
set_property PACKAGE_PIN C9 [get_ports {ALPIDE_DATA_GPIO_dn[9]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[10]}]
set_property PACKAGE_PIN F10 [get_ports {ALPIDE_DATA_GPIO_dn[10]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[11]}]
set_property PACKAGE_PIN E8 [get_ports {ALPIDE_DATA_GPIO_dn[11]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[12]}]
set_property PACKAGE_PIN H9 [get_ports {ALPIDE_DATA_GPIO_dn[12]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[13]}]
set_property PACKAGE_PIN F9 [get_ports {ALPIDE_DATA_GPIO_dn[13]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[14]}]
set_property PACKAGE_PIN H8 [get_ports {ALPIDE_DATA_GPIO_dn[14]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[15]}]
set_property PACKAGE_PIN J10 [get_ports {ALPIDE_DATA_GPIO_dn[15]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[16]}]
set_property PACKAGE_PIN H13 [get_ports {ALPIDE_DATA_GPIO_dn[16]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[17]}]
set_property PACKAGE_PIN J11 [get_ports {ALPIDE_DATA_GPIO_dn[17]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[18]}]
set_property PACKAGE_PIN K8 [get_ports {ALPIDE_DATA_GPIO_dn[18]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[19]}]
set_property PACKAGE_PIN K12 [get_ports {ALPIDE_DATA_GPIO_dn[19]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[20]}]
set_property PACKAGE_PIN K13 [get_ports {ALPIDE_DATA_GPIO_dn[20]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[21]}]
set_property PACKAGE_PIN A9 [get_ports {ALPIDE_DATA_GPIO_dn[21]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[22]}]
set_property PACKAGE_PIN A10 [get_ports {ALPIDE_DATA_GPIO_dn[22]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[23]}]
set_property PACKAGE_PIN A12 [get_ports {ALPIDE_DATA_GPIO_dn[23]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[24]}]
set_property PACKAGE_PIN G11 [get_ports {ALPIDE_DATA_GPIO_dn[24]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[25]}]
set_property PACKAGE_PIN A14 [get_ports {ALPIDE_DATA_GPIO_dn[25]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[26]}]
set_property PACKAGE_PIN A15 [get_ports {ALPIDE_DATA_GPIO_dn[26]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dn[27]}]
set_property PACKAGE_PIN A18 [get_ports {ALPIDE_DATA_GPIO_dn[27]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[0]}]
set_property PACKAGE_PIN D14 [get_ports {ALPIDE_DATA_GPIO_dp[0]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[1]}]
set_property PACKAGE_PIN D13 [get_ports {ALPIDE_DATA_GPIO_dp[1]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[2]}]
set_property PACKAGE_PIN F13 [get_ports {ALPIDE_DATA_GPIO_dp[2]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[3]}]
set_property PACKAGE_PIN C11 [get_ports {ALPIDE_DATA_GPIO_dp[3]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[4]}]
set_property PACKAGE_PIN C12 [get_ports {ALPIDE_DATA_GPIO_dp[4]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[5]}]
set_property PACKAGE_PIN H12 [get_ports {ALPIDE_DATA_GPIO_dp[5]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[6]}]
set_property PACKAGE_PIN E11 [get_ports {ALPIDE_DATA_GPIO_dp[6]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[7]}]
set_property PACKAGE_PIN E10 [get_ports {ALPIDE_DATA_GPIO_dp[7]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[8]}]
set_property PACKAGE_PIN D8 [get_ports {ALPIDE_DATA_GPIO_dp[8]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[9]}]
set_property PACKAGE_PIN D9 [get_ports {ALPIDE_DATA_GPIO_dp[9]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[10]}]
set_property PACKAGE_PIN G10 [get_ports {ALPIDE_DATA_GPIO_dp[10]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[11]}]
set_property PACKAGE_PIN F8 [get_ports {ALPIDE_DATA_GPIO_dp[11]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[12]}]
set_property PACKAGE_PIN J9 [get_ports {ALPIDE_DATA_GPIO_dp[12]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[13]}]
set_property PACKAGE_PIN G9 [get_ports {ALPIDE_DATA_GPIO_dp[13]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[14]}]
set_property PACKAGE_PIN J8 [get_ports {ALPIDE_DATA_GPIO_dp[14]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[15]}]
set_property PACKAGE_PIN K10 [get_ports {ALPIDE_DATA_GPIO_dp[15]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[16]}]
set_property PACKAGE_PIN J13 [get_ports {ALPIDE_DATA_GPIO_dp[16]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[17]}]
set_property PACKAGE_PIN K11 [get_ports {ALPIDE_DATA_GPIO_dp[17]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[18]}]
set_property PACKAGE_PIN L8 [get_ports {ALPIDE_DATA_GPIO_dp[18]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[19]}]
set_property PACKAGE_PIN L12 [get_ports {ALPIDE_DATA_GPIO_dp[19]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[20]}]
set_property PACKAGE_PIN L13 [get_ports {ALPIDE_DATA_GPIO_dp[20]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[21]}]
set_property PACKAGE_PIN B9 [get_ports {ALPIDE_DATA_GPIO_dp[21]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[22]}]
set_property PACKAGE_PIN B10 [get_ports {ALPIDE_DATA_GPIO_dp[22]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[23]}]
set_property PACKAGE_PIN A13 [get_ports {ALPIDE_DATA_GPIO_dp[23]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[24]}]
set_property PACKAGE_PIN H11 [get_ports {ALPIDE_DATA_GPIO_dp[24]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[25]}]
set_property PACKAGE_PIN B14 [get_ports {ALPIDE_DATA_GPIO_dp[25]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[26]}]
set_property PACKAGE_PIN B15 [get_ports {ALPIDE_DATA_GPIO_dp[26]}]
set_property IOSTANDARD SUB_LVDS [get_ports {ALPIDE_DATA_GPIO_dp[27]}]
set_property PACKAGE_PIN A19 [get_ports {ALPIDE_DATA_GPIO_dp[27]}]

set_property IOSTANDARD LVCMOS18 [get_ports {PUSHBUTTON[2]}]
set_property PACKAGE_PIN V32 [get_ports {PUSHBUTTON[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PUSHBUTTON[3]}]
set_property PACKAGE_PIN AA33 [get_ports {PUSHBUTTON[3]}]

# Clock constraints for clocks provided as inputs to the core
# Note: the IP core-level XDC constrains clocks produced by the core, which drive user clocks via helper blocks
# ----------------------------------------------------------------------------------------------------------------------
create_clock -name clk_freerun -period 6.25 [get_ports hb_gtwiz_reset_clk_freerun_in_p]
create_clock -name clk_mgtrefclk1_x0y4_p -period 6.25 [get_ports mgtrefclk1_x0y4_p]
create_clock -name clk_mgtrefclk1_x1y2_p -period 6.25 [get_ports mgtrefclk1_x1y2_p]

# False path constraints
# ----------------------------------------------------------------------------------------------------------------------
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *bit_synchronizer*inst/i_in_meta_reg}]
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_*_reg}]
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_tx_inst/*gtwiz_userclk_tx_active_*_reg}]
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_rx_inst/*gtwiz_userclk_rx_active_*_reg}]
